name: track_expense
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.19.0
  sqflite: ^2.3.3+1
  sqflite_common_ffi: ^2.3.3
  sqflite_common: ^2.5.4
  path_provider: ^2.1.3
  animate_do: ^3.3.4
  cupertino_icons: ^1.0.6
  flutter_local_notifications: ^17.1.2
  timezone: ^0.9.3
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/bg1.jpg
    - assets/profile_icon.png
